# Generated by Django 4.2.7 on 2025-11-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('newborn', 'نوزاد'), ('0-3m', '۰-۳ ماه'), ('3-6m', '۳-۶ ماه'), ('6-9m', '۶-۹ ماه'), ('9-12m', '۹-۱۲ ماه'), ('12-18m', '۱۲-۱۸ ماه'), ('18-24m', '۱۸-۲۴ ماه'), ('2y', '۲ سال'), ('3y', '۳ سال'), ('4y', '۴ سال'), ('5y', '۵ سال'), ('6y', '۶ سال'), ('7y', '۷ سال'), ('8y', '۸ سال'), ('9y', '۹ سال'), ('10y', '۱۰ سال'), ('11y', '۱۱ سال'), ('12y', '۱۲ سال')], max_length=20, verbose_name='سایز'),
        ),
    ]
