# Generated by Django 4.2.7 on 2025-11-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_user_id_0ae59f_idx',
            old_name='orders_ord_user_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_079368_idx',
            old_name='orders_ord_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_created_f0ce29_idx',
            old_name='orders_ord_created_idx',
        ),
    ]
