# Generated by Django 4.2.7 on 2025-11-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_orders_ord_user_idx_orders_orde_user_id_0ae59f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_ref_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره پیگیری پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'پرداخت ناموفق'), ('refunded', 'بازگشت داده شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توکن پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ارسال (تومان)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'پست عادی'), ('express', 'پست پیشتاز')], default='standard', max_length=20, verbose_name='روش ارسال'),
        ),
    ]
