# Generated by Django 4.2.7 on 2025-11-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('category', models.CharField(choices=[('baby', 'نوزاد'), ('girl', 'دخترانه'), ('boy', 'پسرانه')], max_length=10, verbose_name='دسته\u200cبندی')),
                ('season', models.CharField(choices=[('winter', 'زمستان'), ('spring', 'بهار'), ('summer', 'تابستان'), ('fall', 'پاییز')], max_length=10, verbose_name='فصل')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر محصول')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('size', models.CharField(max_length=20, verbose_name='سایز')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'season'], name='products_pr_categor_0acc94_idx'), models.Index(fields=['is_active', '-created_at'], name='products_pr_is_acti_645007_idx')],
            },
        ),
    ]
