# Generated by Django 4.2.7 on 2025-11-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'قرمز'), ('blue', 'آبی'), ('green', 'سبز'), ('yellow', 'زرد'), ('pink', 'صورتی'), ('purple', 'بنفش'), ('orange', 'نارنجی'), ('white', 'سفید'), ('black', 'مشکی'), ('gray', 'خاکستری'), ('brown', 'قهوه\u200cای'), ('navy', 'سرمه\u200cای')], max_length=20, verbose_name='رنگ')),
                ('size', models.CharField(choices=[('newborn', 'نوزاد'), ('0-3m', '۰-۳ ماه'), ('3-6m', '۳-۶ ماه'), ('6-9m', '۶-۹ ماه'), ('9-12m', '۹-۱۲ ماه'), ('12-18m', '۱۲-۱۸ ماه'), ('18-24m', '۱۸-۲۴ ماه'), ('2y', '۲ سال'), ('3y', '۳ سال'), ('4y', '۴ سال'), ('5y', '۵ سال'), ('6y', '۶ سال'), ('7y', '۷ سال'), ('8y', '۸ سال'), ('9y', '۹ سال'), ('10y', '۱۰ سال')], max_length=20, verbose_name='سایز')),
                ('price', models.DecimalField(decimal_places=0, help_text='اگر خالی باشد، قیمت محصول اصلی استفاده می\u200cشود', max_digits=10, verbose_name='قیمت (تومان)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='تصویر (اختیاری)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تنوع محصول',
                'verbose_name_plural': 'تنوع محصولات',
                'ordering': ['product', 'color', 'size'],
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_stock_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_226e74_idx',
            old_name='products_pr_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_season_170a5a_idx',
            old_name='products_pr_season_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_price_9b1a5f_idx',
            old_name='products_pr_price_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_created_bce1a7_idx',
            old_name='products_pr_created_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'size')},
        ),
    ]
