# Generated by Django 4.2.7 on 2025-11-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_product_d800fc_idx',
            old_name='reviews_rev_product_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_user_id_eeecea_idx',
            old_name='reviews_rev_user_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_rating_2db6dd_idx',
            old_name='reviews_rev_rating_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_created_03e07d_idx',
            old_name='reviews_rev_created_idx',
        ),
    ]
